version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: contract_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-contractdb}
    ports:
      - "5432:5432"
    restart: unless-stopped

  cache:
    image: redis:7-alpine
    container_name: contract_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: contract_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    restart: unless-stopped

volumes:
  postgres_data: